const RENDER_PROPS = {
  TITLE: "전국민 투표앱! 코리아 투표앱",
  STYLE: {
    FORM: "FORM",
    VOTE_FORM:"VOTE_FORM",
    VOTE:"VOTE"
  } 
};
const MESSAGE = {
  CREATE_SUCCESS: "CREATE_SUCCESS",
  UPDATE_SUCCESS:"UPDATE_SUCCESS",
  UNAUTHORIZED:"UNAUTHORIZED",
  USER_DONE:"USER_DONE",
  GET_ERROR: "CANNOT_FIND_VOTE_INFO",
};

const USER_STATUS={
  GUEST:"GUEST",
  USER:"USER",
  OWNER:"OWNER"
}

module.exports = { RENDER_PROPS, MESSAGE ,USER_STATUS};
